name: 'Tools Notify'
description: 'Notification action for tools repository'
author: 'mswnlz'
inputs:
  message:
    description: 'The message to print'
    required: false
    default: 'Hello from Tools Action!'
runs:
  using: 'node20'
  main: 'index.js'
